### ISSUE TITLE
Possible mac unnecessary dependencies.

### ISSUE THREAD

**Issue by crluna** [SpineML/SpineCreator#104]
When trying to build it I got a dependency error, the relevant part of the error says:

Found X11: /usr/X11R6/lib/libX11.dylib
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28") 
-- checking for module 'xaw7'
--   package 'xaw7' not found
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  BrahmsLibFind.cmake:121 (pkg_check_modules)
  CMakeLists.txt:140 (include)

CMake Error at BrahmsLibFind.cmake:127 (message):
  You need libXaw7.  On Debian/Ubuntu try `sudo apt-get install libxaw7-dev`
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)

I was told perhaps this is an unnecessary dependency.

**Comment by sebjameswml** [comment]
Can you put this into the brahms issue list? https://github.com/segbjameswml/brahms

**Comment by crluna** [comment]
Thanks for the promt reply and I have put it in the suggested place.

**Comment by sebjameswml** [comment]
Closing as it's a BRAHMS issue.
