### ISSUE TITLE
Powers are not allowed in Math Inline

### ISSUE THREAD

**Issue by AdamRTomkins** [SpineML/SpineCreator#110]
I am having issues using powers with the ^ syntax within a regime.

The simplest reproducible example would be using the Math Inline = v^2

which gives the error "MathInline:" contains unrecognised token v^2

For extra information, I was able to use the dummy Math 1^2 just not a variable^2

**Comment by ajc158** [comment]
Hi,

MathInline used C syntax, for which ^ is not used for raising to a power
(it is a bitwise operation), so we don't support that syntax (and really
should flag the 1^2 case as we don't support that!). We do, however,
support a set of c functions - so the correct syntax for v^2 is pow(v,2).
Or v*v.

Alex

On 14 April 2016 at 17:20, Adam Tomkins <notifications@github.com> wrote:

> I am having issues using powers with the ^ syntax within a regime.
>
> The simplest reproducible example would be using the Math Inline = v^2
>
> which gives the error "MathInline:" contains unrecognised token v^2
>
> For extra information, I was able to use the dummy Math 1^2 just not a
> variable^2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/110>
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk
