### ISSUE TITLE
Experiment interface needs a "duplicate experiment" button

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#112]
Simple as that really.

**Comment by ajc158** [comment]
One of my branches has this -  I'll have a look

**Comment by sebjameswml** [comment]
Great! I think we need a hackathon target which is "merge in all the good
stuff from Alex's branches" ;)

On 28 April 2016 at 14:15, Alex Cope <notifications@github.com> wrote:

> One of my branches has this - I'll have a look
> On 28 Apr 2016 2:13 p.m., "Seb James" <notifications@github.com> wrote:
>
> > Simple as that really.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SpineML/SpineCreator/issues/112>
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/112#issuecomment-215419293>
>



-- 
Research Associate in Computational Neuroscience
Adaptive Behaviour Research Group
Dept. of Psychology

**Comment by ajc158** [comment]
Merged manually in 65853c3
