### ISSUE TITLE
Metadata should be incorporated into the SpineML model as annotations

### ISSUE THREAD

**Issue by mondus** [SpineML/SpineCreator#113]
Standardized XML annotations are a much cleaner approach and therefore should be the preferred method rather than having a custom metadata format.

**Comment by mondus** [comment]
Metadata file currently contains data on Populations, Projections, Generic Inputs

**Comment by sebjameswml** [comment]
We need to add code to read in the old metaData.xml format so that our existing models read, but write out that meta data into the model.xml in the new annotations format.

**Comment by sebjameswml** [comment]
@mondus I've looked for "XML annotations" and find a lot of material about standardized XSL annotations, but nothing that looks like a standard annotation format to go in an XML file, alongside one's XML. What did you mean by Standardized XML annotations?

@ajc158 Where did you get to with annotation code, and where is it (can you point me at any code?).

**Comment by mondus** [comment]
@sebjameswml By standardised, I mean that we should have a schema for any meaningful annotations which are documented. Annotations could of course be anything but there will be a subset of these which are understood by the SpineCreator software.

**Comment by ajc158** [comment]
Hi, 

Annotations for network components that SpineCreator annotates with metadata are in the annotations branch - this branch loads both formats (separate metadata and annotated) , but saves to annotated. Should be tested with all models we have then merged to master

**Comment by sebjameswml** [comment]
Thanks for the extra info chaps. I'll take a look at the annotations branch, rebase it with master and try it out. I really want some text fields in SpineCreator into which I can write notes about the decisions I'm making with models.

**Comment by sebjameswml** [comment]
Closing this ticket now, will replace with a ticket to create UI features for network annotations.
