### ISSUE TITLE
Add support for project files with XML comments

### ISSUE THREAD

**Issue by pgleeson** [SpineML/SpineCreator#128]
Currently loading of project/component files fails if there are XML comment blocks...

Trying to generate SpineML from NeuroML2/LEMS with @ajc158

**Comment by sebjameswml** [comment]
Hi @pgleeson, can you provide a sample file that causes the problem?

**Comment by sebjameswml** [comment]
Though I guess I could just add some random comments to an existing component file...

**Comment by sebjameswml** [comment]
Try the branch ignore_xml_comments which contains commit af68ea8. This should handle XML comments in most locations in the component and network files. Let me know how you get on.

**Comment by sebjameswml** [comment]
Closing; code merged into master.

**Comment by pgleeson** [comment]
Thanks @sebjameswml, I'll try it out.
