### ISSUE TITLE
The window which you get to from a menu item called "Settings" is called "Preferences"

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#130]
Choose one or the other.

**Comment by ajc158** [comment]
Careful before trying to change this - Qt adjusts the name to match the standard naming on the OS it is on - so on OSX that menu option is Preferences. The issue is that we need OS detection to change the window title to 'Options' if not on OSX.

Alex

**Comment by ajc158** [comment]
Fixed def6bcc
