### ISSUE TITLE
URGENT: SpineCreator crashes on loading a model with a CSV connection to a WU

### ISSUE THREAD

**Issue by ajc158** [SpineML/SpineCreator#131]
Under certain circumstances it seems that the parent is not set, leading to a crash on trying to access its members.

**Comment by sebjameswml** [comment]
Uh oh

**Comment by ajc158** [comment]
Fixed problem 1: import_parameters_from_xml was called before setParent, but generates a filename using parent - however filename generation during model load is going to fail anyway, and is not necessary as UUIDs are used until save, so I've removed it. (BTW, this only happens when there is no existing binary file, as the number of connections is too small anyway!)

**Comment by ajc158** [comment]
Fixed in 6f7374f
