### ISSUE TITLE
Plan for text annotations

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#133]
Hi @ajc158  & @mondus 

I'm just merging Alex's annotations code into master in SpineCreator. That means that the SpineCreator metadata will live in LL:Annotations elements rather than in a separate file. Something like this:

```xml
        <LL:Projection dst_population="GPeTI">
            <LL:Annotation>
                <SpineCreator>
                    <DrawOptions style="0" showlabel="0"/>
                    <start x="2.36575" y="-6.80908"/>
                    <curves>
                        <curve>
                            <C1 xpos="3.36575" ypos="-6.80908"/>
                            <C2 xpos="2.03364" ypos="-8.03939"/>
                            <end xpos="2.06575" ypos="-7.10908"/>
                        </curve>
                    </curves>
                </SpineCreator>
            </LL:Annotation>
            <LL:Synapse>... etc
```
Once I'm happy with this (there's just a small bug still to fix for pythonscript_connections), I can then start incorporating text annotations into my models. I want to do this so that I can incorporate notes about the references I've used to make choices about the component and network features of my models. I want to make it possible to view and edit these text notes within the SpineCreator user interface.

First I wondered whether to allow SpineCreator to read/edit a sort of non-spinecreator specific text note like this:

```xml
<LL:Annotation>
  <Text>This is a note about this object</Text>
  <SpineCreator>
    <!-- SpineCreator stuff like curves etc here -->
  </SpineCreator>
</LL:Annotation>
```
I like this, because adding a note about a projection, population or component is a generic thing to do and doesn't seem like it should be "tied" to SpineCreator, even if SpineCreator knows how to add/view/edit/delete those texts.

Alternatively we place the text note inside the SpineCreator element:
```xml
<LL:Annotation>
  <SpineCreator>
    <Text>This is a note about this object</Text>
    <!-- rest of the SpineCreator stuff like curves etc here -->
  </SpineCreator>
</LL:Annotation>
```
This could be better, because I can imagine I might want to have notes about specific elements of the enclosing population, component or projection. For example, I might want (for a component):
```xml
<LL:Annotation>
  <SpineCreator>
    <Text param="tau_syn">This is a note about a specific parameter and the reference from which I obtained its value</Text>
    <Text param="v_offset">This is a note about another specific parameter</Text>
    <!-- rest of the SpineCreator stuff like curves etc here -->
  </SpineCreator>
</LL:Annotation>
```
This becomes a bit more SpineCreator specific because the attribute "param" is only understood by SpineCreator and is not part of the SpineML schema.

I'll go for this unless anyone objects.

Seb

**Comment by mondus** [comment]
This looks great @sebjameswml !

P

**Comment by sebjameswml** [comment]
I went with:
```xml
<LL:Annotation>
  <SpineCreator>
    <Text key="tau_syn">This is a note about a specific parameter and the reference from which I obtained its value</Text>
    <Text key="v_offset">This is a note about another specific parameter</Text>
    <!-- rest of the SpineCreator stuff like curves etc here -->
  </SpineCreator>
</LL:Annotation>
```
Using "key" instead of "param". They key can refer to a parameter, state variable, regime or whatever has that text as its identifier.
