### ISSUE TITLE
Error when installing SpineML_PreFlight

### ISSUE THREAD

**Issue by benoit-girard** [SpineML/SpineCreator#152]
I am trying to install SpineML on macOS, I am following the instructions provided at: https://spineml.github.io/spinecreator/source/

When I reach the `SpineML_PreFlight` step, after launching `make -j4`, I get an error concerning the `abs` function used in `rng.cpp`:

> Scanning dependencies of target spinemlpreflight
[ 19%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/component.cpp.o
[ 19%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/experiment.cpp.o
[ 19%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/connection_list.cpp.o
[ 19%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/fixedvalue.cpp.o
[ 23%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/modelpreflight.cpp.o
[ 28%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/normaldistribution.cpp.o
[ 33%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/propertycontent.cpp.o
[ 38%] Building CXX object src/CMakeFiles/spinemlpreflight.dir/rng.cpp.o
/Users/girard/brainModel/testsSpineML/SpineML_PreFlight/src/rng.cpp:28:16: error: call to 'abs' is ambiguous
    rd->seed = abs(rd->seed * rd->a_RNG + rd->c_RNG);
               ^~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:111:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:113:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:761:1: note: candidate function
abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:765:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return ::fabs(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:769:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return ::fabsl(__lcpp_x);}
^
1 error generated.
make[2]: *** [src/CMakeFiles/spinemlpreflight.dir/rng.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/spinemlpreflight.dir/all] Error 2
make: *** [all] Error 2

Any idea how to solve that?

**Comment by ajc158** [comment]
Hi,

Looking at the error trace I would suggest editing the suggested line and
changing 'abs' to 'llabs' - that should be safe to do. We will have a look
and check if the change is platform independent or not and apply a fix to
the repository if you find that it works.

Thanks,
Alex

**Comment by benoit-girard** [comment]
Thanks a lot for your fast reply.
I tried, it now compiles, but I get the following warning that could be of interest:

> /Users/girard/brainModel/testsSpineML/SpineML_PreFlight/src/rng.cpp:28:16: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
    rd->seed = llabs(rd->seed * rd->a_RNG + rd->c_RNG);
               ^
/Users/girard/brainModel/testsSpineML/SpineML_PreFlight/src/rng.cpp:28:16: note: remove the call to 'llabs' since unsigned values cannot be negative
    rd->seed = llabs(rd->seed * rd->a_RNG + rd->c_RNG);
               ^~~~~
1 warning generated.

**Comment by ajc158** [comment]
Interesting, thanks @sebjameswml ?

**Comment by sebjameswml** [comment]
At a guess, prefixing abs with std:: would be the best fix. I'm going to take a look now. Really sorry to have missed this for so long!

**Comment by sebjameswml** [comment]
See 930a6c7 in which I've corrected all the ambiguous calls to abs(), log() and exp(), which previous worked "on a wing and a prayer" without the std:: qualifier on gcc/icc though with a couple of (valid) compiler warnings emitted by clang 10 (which I don't usually use). This change compiles without errors/warnings with clang 10, gcc 9.3 (both on Ubuntu 20.04) and icc 19.0.5. @benoit-girard if you have a chance, perhaps you could verify that it compiles for you? Sorry again for missing this request for help!

**Comment by sebjameswml** [comment]
It should fix the follow up warning, that you posted, too!

**Comment by sebjameswml** [comment]
I made the corresponding change to the rng.h in SpineML_2_BRAHMS here: https://github.com/SpineML/SpineML_2_BRAHMS/commit/ba5c06d31ab00bca45802100ee5e8518192ddbec

**Comment by sebjameswml** [comment]
As a final comment, the C++ standard library now includes high quality pseudo random number generators, including the Mersenne Twister algorithm AND it has both 32 and 64 bit versions (rng.cpp/h codes the 32 bit version only, which may cycle round to the start of its sequence in an application which requires a large quantity of random numbers). I coded up a nice wrapper around these in morphological: https://github.com/ABRG-Models/morphologica/blob/master/morph/Random.h which you can use under the terms of the GPL if it's useful to you.

**Comment by benoit-girard** [comment]
I will check compilation sometimes soon, I will let you know how it worked.

**Comment by benoit-girard** [comment]
This worked fine, no error, no warning.
Thanks!

**Comment by sebjameswml** [comment]
Brilliant. Thanks very much for taking the time to test!
