### ISSUE TITLE
How to build BRAHMS on macOS?

### ISSUE THREAD

**Issue by benoit-girard** [SpineML/SpineCreator#153]
Following the installation instructions of spineML on macOS (https://spineml.github.io/spinecreator/source/), I am stuck at the BRAHMS step. When trying:
`cmake -DSTANDALONE_INSTALL=ON -DCOMPILE_WITH_X11=OFF \
       -DLICENCE_INSTALL=OFF -DCMAKE_INSTALL_PREFIX=/Users/yourname ..`

I have a linking error I am not able to interpret:
-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /miniconda3/bin/x86_64-apple-darwin13.4.0-clang
-- Check for working C compiler: /miniconda3/bin/x86_64-apple-darwin13.4.0-clang -- broken
CMake Error at /usr/local/Cellar/cmake/3.14.6/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/miniconda3/bin/x86_64-apple-darwin13.4.0-clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/girard/brainModel/testsSpineML/brahms/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_23ebd/fast 
    /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_23ebd.dir/build.make CMakeFiles/cmTC_23ebd.dir/build
    Building C object CMakeFiles/cmTC_23ebd.dir/testCCompiler.c.o
    /miniconda3/bin/x86_64-apple-darwin13.4.0-clang   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_23ebd.dir/testCCompiler.c.o   -c /Users/girard/brainModel/testsSpineML/brahms/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_23ebd
    /usr/local/Cellar/cmake/3.14.6/bin/cmake -E cmake_link_script CMakeFiles/cmTC_23ebd.dir/link.txt --verbose=1
    /miniconda3/bin/x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs  CMakeFiles/cmTC_23ebd.dir/testCCompiler.c.o  -o cmTC_23ebd 
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_23ebd] Error 1
    make: *** [cmTC_23ebd/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/girard/brainModel/testsSpineML/brahms/build/CMakeFiles/CMakeOutput.log".
See also "/Users/girard/brainModel/testsSpineML/brahms/build/CMakeFiles/CMakeError.log".

Any hint what might be the problem?

**Comment by sebjameswml** [comment]
You don't need to build SpineML_2_BRAHMS - it just needs to be placed somewhere sensible. Check the install instructions again

**Comment by sebjameswml** [comment]
However, I see you are right - you ARE instructed to cmake && make...

**Comment by sebjameswml** [comment]
Oh, duh, sorry. It's *BRAHMS* you're working with...
Right, now that I'm oriented, I'm not sure why your linker step isn't working, but you can investigate a little deeper with 
```
make VERBOSE=1
```
which will show you the exact compiler commands being executed. Perhaps that will offer a clue.

**Comment by sebjameswml** [comment]
Closing this ticket; any issues that are in the brahms code will be found in issues on https://github.com/BRAHMS-SystemML/brahms
