### ISSUE TITLE
Improve experiment output scheme

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#24]
Some reworking of the way that experiment data is output is required. In some cases, data needs to be output into time-stamped directories - this is probably a "mode" that a user would enable only when required.

**Comment by ajc158** [comment]
Ok, so my build has a little box where the user can choose an output subdirectory. This seems sensible and the option to add a timestamp would be nice too.

**Comment by sebjameswml** [comment]
I think this may be stale now. Outputting into time-stamped directories is something I would probably do by calling the backend from a script:
```bash
for m in ../model_dir*; do
  ./convert_script_s2b -m $m -e0 -o temp/output$i
  # increment i
done
Recent work in per_expt_graphs which auto-generates a per-experiment output directory ensures that the results of the last run in a particular model/experiment are retained.

**Comment by sebjameswml** [comment]
Also, we have a "per-experiment output" ticket - Issue#114 so closing this ticket.
