### ISSUE TITLE
Auto-colour the connections based on connectivity

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#43]
Create an algorithm which takes the connectivity name and generates a colour from the name. This way, one to one would always be a certain colour, all-to-all likewise, and so on.

**Comment by ajc158** [comment]
I think this is pretty much done??

**Comment by sebjameswml** [comment]
Yes, it is. Fixed with commits around 956facb8c3408f10b768b92551623a39b3bb0db4
