### ISSUE TITLE
Segfault on running experiment

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#44]
Twice in a row I got an error when trying to run the 'channel selection' experiment in the model at https://github.com/ABRG-Models/abrg_local/commit/9b49a6e65009d3a0879d71d91fa1f270df8a05ff
Third time the experiment ran fine.

Error messages (after all the usual junk):
/usr/bin/brahms: line 76:   961 Segmentation fault      (core dumped) brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
Failed to run output.script on the experiment.xml. Falling at the last hurdle.

and

/usr/bin/brahms: line 76:  1137 Segmentation fault      (core dumped) brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
Failed to run output.script on the experiment.xml. Falling at the last hurdle.

**Comment by ajc158** [comment]
Ok, this seems unlikely to be debugged now - hopefully it'll be cleaned up in due course
