### ISSUE TITLE
Remove "batch" button

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#53]
The batch button's functionality should be covered with the proposed "convert script specifying experiment and parameter change" feature, e.g.:

convert_script -m path/to/model -e2 --paramchange="llbn_left_weight=3.4" --paramchange="llbn_right_weight=2.3" -o /path/to/outputdir

It can therefore be removed. A more complete "Batch UI" is proposed as a future development.

**Comment by ajc158** [comment]
Not using this anymore - the command line format + python is currently the way I'm doing this

**Comment by sebjameswml** [comment]
So does the batch button need to be removed, or has it already gone?

**Comment by ajc158** [comment]
Gone
