### ISSUE TITLE
On exit, SC asks to save changes multiple times

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#57]
I've been switching frequently between two models, A & B, without quitting SpineCreator between loading each one. Although I save my work in model A, when I exit SpineCreator I receive multiple popups asking what I want to do with unsaved changes, meaning I end up saving an 'old' version of the model I was working on over the newer version I just saved.

**Comment by sebjameswml** [comment]
Hi @TACD I just pushed commits into master which improve the handling of two simultaneously open projects. This was issue:115

**Comment by sebjameswml** [comment]
Hi @TACD I just tried this and I'm fairly sure my version of SpineCreator happily works with two projects and only saves changes on exit for the one that has genuinely changed, so I'm closing this. Please re-open if you believe this problem still exists. Cheers, Seb.
