### ISSUE TITLE
Component UI: If you create a second Regime, it occludes the first

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#68]
A workaround is to close and reopen the project. This'll be a graphviz problem.

**Comment by ajc158** [comment]
Can't reproduce when creating a new component in a new project, or when adding a second regime to an existing component

**Comment by mondus** [comment]
This has been pretty bullet proof for a while now. Perhaps its your specific machine or Graphviz version. Can you describe a workflow which causes this so it can be reproduced.

**Comment by sebjameswml** [comment]
Well, I can't reproduce it either, so I'll close this.
