### ISSUE TITLE
Consider removing Version Control Interface

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#72]
I think this is a sensible move; a version control interface isn't really necessary, it's only currently implemented for mercurial, and it's not core to SpineCreator's reason for existence. It's code that would have to be maintained in a project which is already plenty big enough for the current developer team. I'm not aware of anyone using it, either - @ajc158 - do you use it?

**Comment by ajc158** [comment]
Hi Seb,

I do use the system, and it ties into a larger part of the SpineCreator philosophy - we want people to use things like version control, and providing an in-program interface allows them to do this without requiring them to need to learn to use a terminal. Maybe they will then transition to the terminal, but I think it gives a nice entry point without adding much code overhead...

**Comment by sebjameswml** [comment]
Hello Alex,

I'm still not convinced - there's not much code to maintain at present (556 lines) but then there's not too much utility either and support for a full range of mercurial functionality as well as git, svn and perhaps cvs and bazaar would add hundreds of additional lines of code.

I don't think an in-program interface will make much difference to whether people use version control in their projects if they're not already aware of it or comfortable using it. I'd redefine the SpineCreator reason for existence to be as a graphical neural network editor (for SpineML) and execution front-end - just that is enough to appeal to all modellers, whether they are experienced programmers or not.

I would still lose this as a feature and allow users to make use of the version control interface of their choice, whether it be command line or a dedicated version control GUI. Kevin is in agreement here.

**Comment by sebjameswml** [comment]
Closing this issue - the version control menu stays.
