### ISSUE TITLE
Consider whether multiple open projects is a feature to maintain/keep

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#73]
I've suggested this because I see bugs occasionally when I have multiple open projects, so I tend to avoid this. It's nothing repeatable that I can open a specific issue for, though.

Possible approaches would be to either:

Fix any bugs with multiple open projects and maintain the multiple open projects feature. Perhaps code review the multiple projects code.

or:

Simplify code so that it's one project per instance of SpineCreator. How much work to remove this feature? Is it safe to run multiple instances of SpineCreator? What happens if user opens the same project with separate instances? Should be fairly safe, because SC works on a temp copy of the model at all times, only writing to the original directory when you "save project". What about any QSettings variables?

**Comment by ajc158** [comment]
I think we should hunt down the bugs - having multiple projects means that things like copy/paste between projects can be more naturally supported. Multiple instances of SpineCreator will add a raft of issues that will break many things and therefore be a larger task than just sorting out the multiple project bugs (for instance all settings and scripts)

**Comment by sebjameswml** [comment]
Ok, I guess there's not a very good reason for removing the multiple project code. If it could significantly reduce the code count/complexity for minimal loss of utility, it'd be worth doing, but your point about copying and pasting of items between projects is good.
