### ISSUE TITLE
Problems with explicit connection lists

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#80]
I'm no longer able to use explicit connection lists in my models - I'm getting two different but similar error messages.

The first I get when trying to save or run a model that includes any explicit connection lists - "Could not open temporary file ‘/home/tacd/.local/share/BLANK/SpineCreator’ for Explicit Connection"

The second only seems to occur when I try to apply an explicit connection list to a non-synaptic (i.e. green) connection - "cv_connection::import_csv(QString): Could not open temporary file ‘/home/tacd/.local/share/BLANK/SpineCreator’ for Explicit Connection"

**Comment by sebjameswml** [comment]
Hi Dave, have you git pulled recently? If so, it's likely that this is a side effect of some code I recently committed.

**Comment by TACD** [comment]
I have! Should I be using the 'Release' version instead of 'Debug' for now?

I just found out that reimporting the connection lists seems to sometimes fix the second error - can't fix the first one yet though

**Comment by sebjameswml** [comment]
Ok. Which of your models is showing the problem? Is it committed into abrg_local? If so I can try to reproduce the error.

**Comment by TACD** [comment]
The latest version of SP_Enk_Network on the weibull branch is showing the first error on load/save, and gives me the second one when I try to reimport the gap junction connection lists. I tried removing the gap junctions entirely and re-importing the others and that seemed to work (but I've reverted to the broken version for now).

**Comment by sebjameswml** [comment]
Yes, it's my changes to connection.cpp. For now, check out the new branch abrg_stable_201501_1 which should work - that is, it's pre-my changes.

**Comment by sebjameswml** [comment]
a48de40 in branch abrg_stable_201501 fixes the first error - the one on load/save.

It also seems to be ok when I re-import the gap junction connectivity; Dave can you test?

**Comment by TACD** [comment]
Yep, this works, thanks!
