### ISSUE TITLE
Import CSV list of weights may be broken with an All to All connection

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#81]
This came up when Alex B tried this: He has all to all connectivity between two populations. He set the weight update component to have a list of weights, which he uploaded into SC using a CSV file. When I ran the model, he got index errors, despite presenting the correct number of weights in his list.

**Comment by sebjameswml** [comment]
Ah, excellent - I have the same problem in the Oculomotor model, so I can try to debug this now.

**Comment by ajc158** [comment]
It is possible I may have fixed this in a different branch - will have a
look...

On 15 September 2015 at 14:28, Seb James <notifications@github.com> wrote:

> Ah, excellent - I have the same problem in the Oculomotor model, so I can
> try to debug this now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/81#issuecomment-140393222>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk

**Comment by sebjameswml** [comment]
Ooh, that'd be good...

**Comment by sebjameswml** [comment]
Ok, the problem that *I'm* having is related to file format - I was using a stale routine I'd written to write out some mapped weights which omitted the index.

Alex B still has a problem with weights imported from CSV.

**Comment by ajc158** [comment]
I think this is the issue where the filename for the connection was not set when doing a csv import to an empty connection, leading to a file error... if so we can close it

**Comment by sebjameswml** [comment]
Closing this as probably fixed with my connectivity fixes around commit fe6edd6 and 5047fa2
