### ISSUE TITLE
Graphs interface has bug(s)?

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#82]
I just had a situation where the Graphs interface was showing crazy results for a simple network. After a while spent investigating what might be wrong with the network output, I found that the output is fine, it was the SpineCreator graphing that had gone wrong.

**Comment by sebjameswml** [comment]
I have a demo of the problem. 

The data is here: https://sebjames.zapto.org/owncloud/index.php/s/PxKYU0sKdNMhemv

On a freshly started SpineCreator (from the master branch), go to the Graphs interface and use the "folder" icon to load the log "SNr_v_log.bin". From this, make a graph of index 8. You should see 3 spikes, then a buildup towards a 4th spike, then a drop to the 'C' (as in the Izhikevich ABCD model) reset value for the voltage, then a jump to voltage >  Vpeak.

It looks like this:

![sc_graphs_iface_wrong](https://cloud.githubusercontent.com/assets/130308/10135823/cd108d82-65e8-11e5-8964-e5d7f7e76641.png)

Opening the same log using the load_sc_data function from SpineCreator/analysis_utils/matlab/ shows sensible data:

a = load_sc_data ('STN_v_log.bin',60) % The log contains data for 60 neurons
plot (a(9,:)) % Index 9 in matlab/octave is index 8 in the SC Graphs interface.

Gives:

![octave_load_sc_data_right](https://cloud.githubusercontent.com/assets/130308/10135834/e280c5ec-65e8-11e5-9be7-3c9670769682.png)

**Comment by ajc158** [comment]
Looks like one of those graphs is the STN, and one the snr...

**Comment by sebjameswml** [comment]
Oh, bother so they are. Hold on. Yes, it's the component output that's at fault, rather than the interface.

**Comment by sebjameswml** [comment]
Back to debugging the component. Not good.
