### ISSUE TITLE
Error when importing explicit connection list

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#86]
When first attempting to convert a spike source -> population projection from the default to an explicit connection list, I receive the following error:

csv_connection::import_csv(QString): Could not open temporary file '/home/dbuxton/.local/share/BLANK/SpineCreator' for Explicit Connection

If I hit 'OK' on the dialog box the property window will now be showing a connection type of 'explicit connection', but the list will be empty. If I then save the model I receive the following error:

Could not open temporary file '/home/dbuxton/.local/share/BLANK/SpineCreator/conn_Cortex_CH3_to_D2_MSNs_syn1.bin' for Explicit Connection

After hitting 'OK' on this dialog box I am then able to import an explicit connection list as normal for that connection.

**Comment by sebjameswml** [comment]
See [2016_hackathon_codecomment_refactor 649f29a] for a fix.
