### ISSUE TITLE
Problem with randomised connection delay

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#88]
Under the 'connectivity' tab, when I try to set a 'random' connection delay of either 'normal' or 'uniform' on an 'All to all' connection I get an output error like this:

Executing: brahms   --par-ShowGUI=0 --par-NamespaceRoots="/usr/lib/spineml-2-brahms/:/home/tacd/Documents/SpineML_2_BRAHMS/Namespace:/home/tacd/Documents/SpineML_2_BRAHMS/tools" "/home/tacd/Documents/SpineML_2_BRAHMS/temp/run/sys-exe.xml" from pwd: /home/tacd/Documents/SpineML_2_BRAHMS/temp/run
W2    0.001339       have p delays
W2    0.001363       have p delays: right size
W2    0.001387       4.29497e+10 = moo
W4    0.103584       FINISHED
E_STD: std::bad_alloc
    whilst firing EVENT_STATE_SET on Cortex_CH3_to_D1_MSNs_Synapse_0_weight_update
Failed to run output.script on experiment1.xml. Falling at the last hurdle.

**Comment by sebjameswml** [comment]
Hi @TACD do you get this with a generic connection or a regular projection? You could try to see what happens in my delay-fixing branches of SpineML_2_BRAHMS (expt_delay_change_option) and SpineML_PreFlight (expt_delay_change), and see what result you get. Do this on copies of your models, just in case!

**Comment by sebjameswml** [comment]
Ping @TACD could you test this on latest master versions of SpineCreator, SpineML_2_BRAHMS and SpineML_PreFlight?

**Comment by TACD** [comment]
This seems to be working fine now!
