### ISSUE TITLE
Unable to use 'array of constant inputs'

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#89]
When trying to use the 'array of constant inputs' option in creating an experiment, any number entered in the 'Value' column is immediately reset to zero. The 'fill' button also doesn't work.

**Comment by AdamRTomkins** [comment]
Constant array input also fails to load a ConstantInputArray that has been specified correctly in SpineML outside of spine creator

**Comment by ajc158** [comment]
OK, I really need to fix this!

**Comment by sebjameswml** [comment]
This just bit me too.

**Comment by ajc158** [comment]
Fixed in b21b3bf
