### ISSUE TITLE
Use -Wall to crush some easy minor warnings and make the build clean

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineCreator#93]

**Comment by ajc158** [comment]
Not a good idea as Qt includes raise warnings on several platforms.

**Comment by sebjameswml** [comment]
Do you know which warnings it commonly raises? -Wall is short hand for a bunch of warnings; we could include a subset of warnings to treat as errors that won't mess up Qt on other platforms.

**Comment by SpineML** [comment]
Or we could use -wall and explicitly ignore the warnings raised by Qt
through #pragma warning ignores in specific modules where Qt errors are
raised. These can then be phased out should Qt solve this in future
releases.

On Friday, 5 February 2016, Seb James <notifications@github.com> wrote:

> Do you know which warnings it commonly raises? -Wall is short hand for a
> bunch of warnings; we could include a subset of warnings to treat as errors
> that won't mess up Qt on other platforms.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/93#issuecomment-180308892>
> .
>


-- 
Dr Paul Richmond (Research Fellow) - University of Sheffield
http://www.paulrichmond.staff.shef.ac.uk
p.richmond@sheffield.ac.uk

Department of Computer Science <http://www.sheffield.ac.uk/dcs>
Sheffield NVIDIA CUDA Research Centre
<http://gpucomputing.sites.sheffield.ac.uk/>
Advanced Computing Research Centre <http://www.acrc.com>

**Comment by sebjameswml** [comment]
I've added -Wall for Linux only and have removed all but one warning which comes from Qt code.
