### ISSUE TITLE
New components do not start with a regime, but sim crashes if no regime is present

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#94]
Sometimes I need to create a 'null' component (e.g. the data I want to analyse is on a postsynapse, so I need a 'null' neuron population to project to) - if I forget to manually create a regime for this component the simulation crashes with the error:

E_MODULE_NOT_FOUND: module not found "/home/tacd/Documents/SpineML_2_BRAHMS/Namespace/dev/SpineML/temp/NB/Null/brahms/0/component.so"
    whilst processing "engine->open()"
Failed to run output.script on experiment0.xml. Falling at the last hurdle.

**Comment by sebjameswml** [comment]
Hi Dave, thanks for the issue report. 

@ajc158  - this is a fairly minor problem. Would we say that the omission of a regime is a SpineML error and so we require the user to create one in SpineCreator, even if it's empty, or do we modify SpineML_2_BRAHMS to handle the missing Null component?

**Comment by sebjameswml** [comment]
Alex just ran into this issue again, and it cost him some time; definitely wants fixing.

**Comment by ajc158** [comment]
Fixed in 73af1c7
