### ISSUE TITLE
Import/Export Data

### ISSUE THREAD

**Issue by fdorian88** [SpineML/SpineCreator#96]
I started playing recently with SpineCreator and I built the models I needed, but I don't know how to import an input or export an output. 
Could any of you tell me how to fill in the Command, Host IP and Port?
Thanks.

**Comment by sebjameswml** [comment]
Hi @fdorian88 

First thing is that you need to run the right kind of server for the connection. There are some example servers in SpineCreator/networkserver. There is one server that runs within a matlab or octave session and can feed data to or consume data from the SpineCreator model. There is also a C++ standalone server

Once you have your server set up, you can configure a new Input in your model's "Experiment view" and choose "External input". You can leave "Command" blank, then use whatever is the IP address of the machine you're running the server on. If it's the same machine as your model, then use 127.0.0.1. The port is most likely to be 50091, but should match whatever you set up in the server.

I'd very much recommend trying to run the sample matlab/octave server in the SpineCreator source to try the whole process out. That's a SpineCreator project in SpineCreator/networkserver/matlab/spinemlnet_test.

All the best,

Seb James

**Comment by sebjameswml** [comment]
I assume you've found out how to read the data produced by your model?

**Comment by SpineML** [comment]
Does BRAHMS have an option to output the log data in plain text format?

P

On 3 February 2016 at 16:09, Seb James <notifications@github.com> wrote:

> I assume you've found out how to read the data produced by your model?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/96#issuecomment-179316540>
> .
>



-- 
Dr Paul Richmond (Research Fellow)
EPSRC Doctoral Prize Research Fellow
Royal Academy of Engineering Student Development Fellowship Awardee

Computer Graphics Group
UNIVERSITY OF SHEFFIELD
The Department of Computer Science
Regent Court, 211 Portobello
Sheffield, S1 4DP, UK
http://www.dcs.shef.ac.uk/~paul
p.richmond@dcs.shef.ac.uk

**Comment by ajc158** [comment]
Hi Paul, 
Spike data is output as a CSV file, as it is usually pretty lightweight. Analog data on the other hand is really bulky, and the text file option would rarely be desirable. I have a simple python class which can extract individual columns of data from the analog binary file, so maybe we should bundle that with a simple demo in the simulation packages.

**Comment by SpineML** [comment]
Could you hook Dorian up with the python binary file reader for analogue
data. I don't think that having it included is necessary as long as the
BRAHMS output data is documented. Longer term it would be advantageous to
have some kind of standardised export output feature from the experiment
output visualiser. Binary output is fine as long as we can agree on a
common standard (preferably something simple and well supported). Something
that can be read by gnuplot is a must.

http://gnuplot.sourceforge.net/docs_4.2/node101.html

Perhaps add it to the to do list for the hackathon. I'll add it as a
feature request in the issue tracker.

P

On 4 February 2016 at 09:00, Alex Cope <notifications@github.com> wrote:

> Hi Paul,
> Spike data is output as a CSV file, as it is usually pretty lightweight.
> Analog data on the other hand is really bulky, and the text file option
> would rarely be desirable. I have a simple python class which can extract
> individual columns of data from the analog binary file, so maybe we should
> bundle that with a simple demo in the simulation packages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/96#issuecomment-179716766>
> .
>



-- 
Dr Paul Richmond (Research Fellow)
EPSRC Doctoral Prize Research Fellow
Royal Academy of Engineering Student Development Fellowship Awardee

Computer Graphics Group
UNIVERSITY OF SHEFFIELD
The Department of Computer Science
Regent Court, 211 Portobello
Sheffield, S1 4DP, UK
http://www.dcs.shef.ac.uk/~paul
p.richmond@dcs.shef.ac.uk

**Comment by mondus** [comment]
Moved to feature request #97

**Comment by sebjameswml** [comment]
Look in SpineCreator/analysis_utils/python and  SpineCreator/analysis_utils/matlab for two versions of a "load spinecreator data" script which I wrote - load_sc_data.py/m

**Comment by ajc158** [comment]
Additionally, each log comes with an xml file that describes the data
format - it is this I parse in the python script. The binary is packed
doubles so can definitely be read by GNUplot

On 4 February 2016 at 10:41, Seb James <notifications@github.com> wrote:

> Look in SpineCreator/analysis_utils/python and
> SpineCreator/analysis_utils/matlab for two versions of a "load spinecreator
> data" script which I wrote - load_sc_data.py/m
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/96#issuecomment-179764010>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk

**Comment by fdorian88** [comment]
Thanks for the help everyone, I was able to get the data from the binary file using load_sc_data.m

Kind regards,
Dorian

**Comment by sebjameswml** [comment]
Good stuff, glad it worked.
