### ISSUE TITLE
Export simulation log data in standardised binary format

### ISSUE THREAD

**Issue by mondus** [SpineML/SpineCreator#97]
Relating to Issue #96. Ideally we could add support for exporting standardised data files for simulation logs. Compatibility with gnuplot would be preferable by using either gpbin, edf or avs. http://www.gnuplot.info/docs_4.2/gnuplot.html#x1-130004.2

**Comment by ajc158** [comment]
Think this is done. We have an xml format describing logs and the standard format is packed double binary data, which can be plotted by GNUplot (I'm sure I've done it in the past). Details on stride length are in the xml.

**Comment by ajc158** [comment]
e.g.

<LogReport>
	<AnalogLog>
		<LogFile>EN_a_in_log.bin</LogFile>
		<LogFileType>binary</LogFileType>
		<LogEndTime>500.000000</LogEndTime>
		<LogAll size="8" headings="a_in" type="double" dims=""/>
		<TimeStep dt="0.100000"/>
	</AnalogLog>
</LogReport>

<LogReport>
	<EventLog>
		<LogFile>Cortex_spikeOut_log.csv</LogFile>
		<LogFileType>csv</LogFileType>
		<LogPort>spikeOut</LogPort>
		<LogEndTime>5000.000000</LogEndTime>
		<LogAll size="6" type="int" dims=""/>
		<LogCol heading="t" dims="ms" type="double"/>
		<LogCol heading="index" dims="" type="int"/>
		<TimeStep dt="0.100000"/>
	</EventLog>
</LogReport>

**Comment by SpineML** [comment]
Magic. P

On 4 February 2016 at 10:50, Alex Cope <notifications@github.com> wrote:

> e.g.
>
>
>
> EN_a_in_log.bin
> binary
> 500.000000
>
>
>
>
>
> Cortex_spikeOut_log.csv
> csv
> spikeOut
> 5000.000000
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineCreator/issues/97#issuecomment-179768718>
> .
>



-- 
Dr Paul Richmond (Research Fellow)
EPSRC Doctoral Prize Research Fellow
Royal Academy of Engineering Student Development Fellowship Awardee

Computer Graphics Group
UNIVERSITY OF SHEFFIELD
The Department of Computer Science
Regent Court, 211 Portobello
Sheffield, S1 4DP, UK
http://www.dcs.shef.ac.uk/~paul
p.richmond@dcs.shef.ac.uk

**Comment by mondus** [comment]
Already Done!
